### ISSUE TITLE
hooks grep matches only a singular file type

### ISSUE THREAD

**Issue by brett-james-rocketlab** [kaczor6418/git-hooks-example#3]
The Pre-commit hook only listens for the one file extension. It would be more suitable if you could include a variety of file extensions to have eslint do it's thing.

From what I can see, using .{tsx,js,jsx} is invalid POSIX syntax, so is fairly brittle. (Source: https://stackoverflow.com/questions/10619160/how-do-i-use-the-grep-include-option-for-multiple-file-types ) .

Do you have any other suggestions for using this?

**Comment by kaczor6418** [comment]
Hi, 

I have included a more advanced script in which you can define what file extensions you are interested in. I have used regExp for this. Please let me know, does this solve your issue ;)
